name: peer_chat_flutter
description: A Flutter plugin for peer-to-peer chat functionality.
version: 0.0.1
homepage: https://your-package-homepage.com

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  peerdart: ^0.5.4
  permission_handler: ^10.0.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        dartPluginClass: PeerChatFlutter
      ios:
        dartPluginClass: PeerChatFlutter
